version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      
  pre_build:
    commands:
      - echo "Running tests..."
      - python -m pytest tests/ || echo "No tests found, continuing..."
      
  build:
    commands:
      - echo "Building deployment package..."
      - zip -r function.zip . -x "*.git*" "tests/*" "*.pyc" "__pycache__/*"
      - export DEPLOYMENT_KEY="lambda-deployments/$(date +%Y%m%d-%H%M%S)-${CODEBUILD_BUILD_NUMBER}/function.zip"
      - echo "Deployment key is $DEPLOYMENT_KEY"
      - aws s3 cp function.zip s3://$DEPLOYMENT_BUCKET/$DEPLOYMENT_KEY
      - echo "Creating deployment parameter files using Python..."
      - python -c "import json; import os; params=[{'ParameterKey':'DeploymentBucket','ParameterValue':os.environ['DEPLOYMENT_BUCKET']},{'ParameterKey':'DeploymentKey','ParameterValue':os.environ['DEPLOYMENT_KEY']},{'ParameterKey':'FunctionName','ParameterValue':os.environ['FUNCTION_NAME']}]; open('deployment-params.json','w').write(json.dumps(params,indent=2))"
      - python -c "import json; import os; config={'Parameters':{'DeploymentBucket':os.environ['DEPLOYMENT_BUCKET'],'DeploymentKey':os.environ['DEPLOYMENT_KEY'],'FunctionName':os.environ['FUNCTION_NAME']}}; open('template-config.json','w').write(json.dumps(config,indent=2))"
      - echo "Files created successfully"
      - cat deployment-params.json
      - cat template-config.json

artifacts:
  files:
    - template.yaml
    - deployment-params.json
    - template-config.json
  name: lambda-deployment-$(date +%Y-%m-%d)
