version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      
  pre_build:
    commands:
      - echo "Running tests..."
      - python -m pytest tests/ || echo "No tests found, skipping..."
      
  build:
    commands:
      - echo "Building deployment package..."
      - zip -r function.zip . -x "*.git*" "tests/*" "*.pyc" "__pycache__/*"
      - export DEPLOYMENT_KEY="lambda-deployments/$(date +%Y%m%d-%H%M%S)-${CODEBUILD_BUILD_NUMBER}/function.zip"
      - echo "Deployment key: $DEPLOYMENT_KEY"
      - aws s3 cp function.zip s3://$DEPLOYMENT_BUCKET/$DEPLOYMENT_KEY
      - echo "Creating deployment parameter files..."
      - 'echo "[{\"ParameterKey\":\"DeploymentBucket\",\"ParameterValue\":\"$DEPLOYMENT_BUCKET\"},{\"ParameterKey\":\"DeploymentKey\",\"ParameterValue\":\"$DEPLOYMENT_KEY\"},{\"ParameterKey\":\"FunctionName\",\"ParameterValue\":\"$FUNCTION_NAME\"}]" > deployment-params.json'
      - 'echo "{\"Parameters\":{\"DeploymentBucket\":\"$DEPLOYMENT_BUCKET\",\"DeploymentKey\":\"$DEPLOYMENT_KEY\",\"FunctionName\":\"$FUNCTION_NAME\"}}" > template-config.json'
      - echo "Parameter files created successfully"

artifacts:
  files:
    - template.yaml
    - deployment-params.json
    - template-config.json
  name: lambda-deployment-$(date +%Y-%m-%d)
