version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      
  pre_build:
    commands:
      - echo "Running tests..."
      - python -m pytest tests/
      
  build:
    commands:
      - echo "Building deployment package..."
      - zip -r function.zip . -x "*.git*" "tests/*" "*.pyc" "__pycache__/*"
      
      # Generate unique deployment key
      - export DEPLOYMENT_KEY="lambda-deployments/$(date +%Y%m%d-%H%M%S)-${CODEBUILD_BUILD_NUMBER}/function.zip"
      - echo "Deployment key: $DEPLOYMENT_KEY"
      
      # Upload to S3
      - aws s3 cp function.zip s3://$DEPLOYMENT_BUCKET/$DEPLOYMENT_KEY
      
      # Create parameter file for CloudFormation
      - |
        cat > deployment-params.json << EOF
        [
          {
            "ParameterKey": "DeploymentBucket",
            "ParameterValue": "$DEPLOYMENT_BUCKET"
          },
          {
            "ParameterKey": "DeploymentKey",
            "ParameterValue": "$DEPLOYMENT_KEY"
          },
          {
            "ParameterKey": "FunctionName",
            "ParameterValue": "$FUNCTION_NAME"
          }
        ]
        EOF
        
      # Create template configuration
      - |
        cat > template-config.json << EOF
        {
          "Parameters": {
            "DeploymentBucket": "$DEPLOYMENT_BUCKET",
            "DeploymentKey": "$DEPLOYMENT_KEY",
            "FunctionName": "$FUNCTION_NAME"
          }
        }
        EOF
artifacts:
  files:
    - template.yaml
    - deployment-params.json
    - template-config.json
  name: lambda-deployment-$(date +%Y-%m-%d)
